version: '3'
services:
  spark:
    image: jupyter/all-spark-notebook
    ports:
      -"8888:8888"
      -"4040-4080:4040-4080"
    volumes:
      -./notebooks:/Users/luca/anaconda2/Springboard/Mini-Projects/spark
